import '../models/pagination.dart';
import '../models/venue.dart';

/// Interface for venue management operations.
abstract interface class VenueSource {
  /// Get a paginated list of venues.
  Future<PaginatedList<Venue>> getVenues({
    int offset = 0,
    int limit = 20,
  });

  /// Get a venue by ID.
  Future<Venue> getVenue(int id);

  /// Create a new venue with the provided details.
  ///
  /// ID is auto-generated by the database.
  Future<Venue> createVenue({
    required String name,
    bool isDefault = false,
    String? address,
    String? description,
    String? mapUri,
    bool isFeatured = false,
  });

  /// Update a venue. Uses ValueGetter pattern for nullable fields.
  Future<Venue> updateVenue(
    int id, {
    String? name,
    bool? isDefault,
    String? Function()? address,
    String? Function()? description,
    String? Function()? mapUri,
    bool? isFeatured,
  });

  /// Get a paginated list of soft-deleted venues.
  Future<PaginatedList<Venue>> getDeletedVenues({
    int offset = 0,
    int limit = 20,
  });

  /// Delete a venue (soft delete - sets deletedAtUtc).
  ///
  /// Returns the soft-deleted venue (with `deletedAtUtc` populated) as
  /// echoed by the server, so callers can update local state from the
  /// response without a follow-up fetch.
  Future<Venue> deleteVenue(int id);

  /// Restore a soft-deleted venue.
  Future<Venue> restoreVenue(int id);

  /// Permanently delete a venue.
  /// Only super admin can perform this operation.
  Future<void> hardDeleteVenue(int id);
}
